# production config
version: "3.4"
services:
  web:
    image: "fucr_web"
    build:
      context: ./web
      dockerfile: ./Dockerfile
      target: prod
    environment:
      - NODE_ENV=production
      - DEBUG
      - WEBSITE_URL
      - NEXT_PUBLIC_AFFINIDI_ENV
      - NEXT_PUBLIC_AFFINIDI_API_KEY
